/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atividade;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author ferna
 */
public class telaInicial extends javax.swing.JFrame {
    
    cadastroDeCasa cadastro;
    procurarCasa casa;
    List<Imovel> lista = new ArrayList<>();//criação da List para salvar os imoveis que serao criados
    /**
     * Creates new form telaInicial
     */
    public telaInicial() {
        initComponents();
        configurarFormulario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        botaoCadastro = new javax.swing.JButton();
        textoTelaInicial = new javax.swing.JLabel();
        botaoProcurar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 23, 31));

        botaoCadastro.setBackground(new java.awt.Color(2, 16, 50));
        botaoCadastro.setForeground(new java.awt.Color(0, 126, 167));
        botaoCadastro.setText("Cadastrar uma casa");
        botaoCadastro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoCadastroMouseClicked(evt);
            }
        });

        textoTelaInicial.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        textoTelaInicial.setForeground(new java.awt.Color(0, 126, 167));
        textoTelaInicial.setText("Bem vindo!");

        botaoProcurar.setBackground(new java.awt.Color(2, 16, 50));
        botaoProcurar.setForeground(new java.awt.Color(0, 126, 167));
        botaoProcurar.setText("procurar uma casa");
        botaoProcurar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botaoProcurarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(botaoCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(botaoProcurar)
                .addGap(27, 27, 27))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textoTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(textoTelaInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoProcurar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoCadastroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoCadastroMouseClicked
        cadastro = new cadastroDeCasa();
        cadastro.setLocationRelativeTo(null);
        cadastro.setVisible(true);
        cadastro.setResizable(false);
        
        for (Imovel lista1 : lista) {
            cadastro.receberDados(lista1);
        }
        
        this.dispose();
    }//GEN-LAST:event_botaoCadastroMouseClicked

    private void botaoProcurarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botaoProcurarMouseClicked
        // TODO add your handling code here:
        casa = new procurarCasa();
        casa.setLocationRelativeTo(null);
        casa.setVisible(true);
        casa.setResizable(false);
        
        //passar os dados
        for (Imovel objeto : lista) {
            casa.receberDados(objeto);
        }
        
        this.dispose();
        casa.mostrarDados();
    }//GEN-LAST:event_botaoProcurarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoProcurar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel textoTelaInicial;
    // End of variables declaration//GEN-END:variables

    private void configurarFormulario() {
        
        this.setTitle("Inicio");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
    }
    
    //receber os dados
    public void receberDados(Imovel objeto)
    {
        Imovel tela;
        tela = new Imovel();
        tela.setCategoria(objeto.getCategoria());
        tela.setDescricao(objeto.getDescricao());
        tela.setNomeImovel(objeto.getNomeImovel());
        tela.setTipoDoImovel(objeto.getTipoDoImovel());
        tela.setValorDaVenda(objeto.getValorDaVenda());
        lista.add(tela);
    }
    
    
    
}
