/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calc;

/**
 *
 * @author ferna
 */
public class Clac extends javax.swing.JFrame {
    
    //Variaveis declaradas
    float Valor1, valor2;
    String operador,resultado;

    /**
     * Creates new form Clac
     */
    public Clac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton11 = new javax.swing.JButton();
        button_delete = new javax.swing.JButton();
        button_C = new javax.swing.JButton();
        button_virgula = new javax.swing.JButton();
        button_divPorX = new javax.swing.JButton();
        button_dividir = new javax.swing.JButton();
        button_multiplicar = new javax.swing.JButton();
        button_aoQuadrado = new javax.swing.JButton();
        button_Somar = new javax.swing.JButton();
        button_Subtrair = new javax.swing.JButton();
        button_igualdade = new javax.swing.JButton();
        button_0 = new javax.swing.JButton();
        button_1 = new javax.swing.JButton();
        button_2 = new javax.swing.JButton();
        button_3 = new javax.swing.JButton();
        button_4 = new javax.swing.JButton();
        button_5 = new javax.swing.JButton();
        button_6 = new javax.swing.JButton();
        button_7 = new javax.swing.JButton();
        button_8 = new javax.swing.JButton();
        button_9 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Tela = new javax.swing.JLabel();

        jButton11.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        button_delete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_delete.setText("««");
        button_delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_deleteMouseClicked(evt);
            }
        });
        button_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_deleteActionPerformed(evt);
            }
        });

        button_C.setText("C");
        button_C.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_CMouseClicked(evt);
            }
        });

        button_virgula.setText(",");
        button_virgula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_virgulaMouseClicked(evt);
            }
        });

        button_divPorX.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_divPorX.setText("½");
        button_divPorX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_divPorXMouseClicked(evt);
            }
        });

        button_dividir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_dividir.setText("/");
        button_dividir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_dividirMouseClicked(evt);
            }
        });

        button_multiplicar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_multiplicar.setText("*");
        button_multiplicar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_multiplicarMouseClicked(evt);
            }
        });

        button_aoQuadrado.setText("x²");
        button_aoQuadrado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_aoQuadradoMouseClicked(evt);
            }
        });

        button_Somar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_Somar.setText("+");
        button_Somar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_SomarMouseClicked(evt);
            }
        });

        button_Subtrair.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_Subtrair.setText("-");
        button_Subtrair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_SubtrairMouseClicked(evt);
            }
        });

        button_igualdade.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        button_igualdade.setText("=");
        button_igualdade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_igualdadeMouseClicked(evt);
            }
        });

        button_0.setText("0");
        button_0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_0MouseClicked(evt);
            }
        });

        button_1.setText("1");
        button_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_1MouseClicked(evt);
            }
        });

        button_2.setText("2");
        button_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_2MouseClicked(evt);
            }
        });

        button_3.setText("3");
        button_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_3MouseClicked(evt);
            }
        });

        button_4.setText("4");
        button_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_4MouseClicked(evt);
            }
        });

        button_5.setText("5");
        button_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_5MouseClicked(evt);
            }
        });

        button_6.setText("6");
        button_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_6MouseClicked(evt);
            }
        });

        button_7.setText("7");
        button_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_7MouseClicked(evt);
            }
        });

        button_8.setText("8");
        button_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_8MouseClicked(evt);
            }
        });

        button_9.setText("9");
        button_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_9MouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(118, 118, 118));

        Tela.setBackground(new java.awt.Color(173, 173, 173));
        Tela.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        Tela.setForeground(new java.awt.Color(0, 0, 0));
        Tela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tela, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(button_1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(button_4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_virgula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(button_2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(button_7, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_C, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(button_8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(button_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_aoQuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_Somar, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(button_igualdade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(button_divPorX, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                                    .addComponent(button_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(button_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(button_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(button_Subtrair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(button_dividir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(button_C, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_dividir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(button_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_divPorX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(button_multiplicar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Subtrair, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(button_6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_Somar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(button_igualdade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(button_virgula, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_0, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(button_aoQuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_deleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_deleteActionPerformed

    private void button_7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_7MouseClicked
        Tela.setText(Tela.getText() + "7");
    }//GEN-LAST:event_button_7MouseClicked

    private void button_8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_8MouseClicked
        // TODO add your handling code here:
        Tela.setText(Tela.getText() + "8");
    }//GEN-LAST:event_button_8MouseClicked

    private void button_9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_9MouseClicked
        Tela.setText(Tela.getText() + "9");
    }//GEN-LAST:event_button_9MouseClicked

    private void button_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_4MouseClicked
        Tela.setText(Tela.getText() + "4");
    }//GEN-LAST:event_button_4MouseClicked

    private void button_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_5MouseClicked
        Tela.setText(Tela.getText() + "5");
    }//GEN-LAST:event_button_5MouseClicked

    private void button_6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_6MouseClicked
        // TODO add your handling code here:
        Tela.setText(Tela.getText() + "6");
    }//GEN-LAST:event_button_6MouseClicked

    private void button_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_1MouseClicked
        Tela.setText(Tela.getText() + "1");
    }//GEN-LAST:event_button_1MouseClicked

    private void button_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_2MouseClicked
        Tela.setText(Tela.getText() + "2");
    }//GEN-LAST:event_button_2MouseClicked

    private void button_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_3MouseClicked
        Tela.setText(Tela.getText() + "3");
    }//GEN-LAST:event_button_3MouseClicked

    private void button_0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_0MouseClicked
        Tela.setText(Tela.getText() + "0");
    }//GEN-LAST:event_button_0MouseClicked

    private void button_CMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_CMouseClicked
        Tela.setText("");
        //definir como nulo os valores 1 e 2
        Valor1 = 0;
        valor2 =0;
    }//GEN-LAST:event_button_CMouseClicked

    private void button_SomarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SomarMouseClicked
        Valor1 = Float.parseFloat(Tela.getText());
        operador = "+";
        Tela.setText("");
    }//GEN-LAST:event_button_SomarMouseClicked

    private void button_SubtrairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_SubtrairMouseClicked
        Valor1 = Float.parseFloat(Tela.getText());
        operador = "-";
        Tela.setText("");
    }//GEN-LAST:event_button_SubtrairMouseClicked

    private void button_multiplicarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_multiplicarMouseClicked
        Valor1 = Float.parseFloat(Tela.getText());
        operador = "*";
        Tela.setText("");
    }//GEN-LAST:event_button_multiplicarMouseClicked

    private void button_dividirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_dividirMouseClicked
        Valor1 = Float.parseFloat(Tela.getText());
        operador = "/";
        Tela.setText("");
    }//GEN-LAST:event_button_dividirMouseClicked

    private void button_igualdadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_igualdadeMouseClicked
        if(Valor1==0 && valor2==0){
            Tela.setText("");
            Valor1=0;
            valor2=0;
        }
        else{
            valor2 = Float.parseFloat(Tela.getText());
            
            switch(operador){
                case "+":{
                    resultado = String.valueOf(Valor1 + valor2);
                    break;
                }
                    
                case "-":{
                    resultado = String.valueOf(Valor1 - valor2);
                    break;
                }
                case "*":{
                    resultado = String.valueOf(Valor1 * valor2);
                    break;
                }
                case "/":{
                    resultado = String.valueOf(Valor1 / valor2);
                    break;
                }
            }
            Tela.setText(resultado);
            resultado.equals("");
        }
    }//GEN-LAST:event_button_igualdadeMouseClicked

    private void button_virgulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_virgulaMouseClicked
        if(Tela.getText().equals(""))
        {
            Tela.setText("0.");
        }
        else{
            Tela.setText(Tela.getText() + ".");
        }
    }//GEN-LAST:event_button_virgulaMouseClicked

    private void button_deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_deleteMouseClicked
        if(Tela.getText().equals("")){
            
        }
        else
            Tela.setText(Tela.getText().substring(0 ,Tela.getText().length() -1));
    }//GEN-LAST:event_button_deleteMouseClicked

    private void button_aoQuadradoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_aoQuadradoMouseClicked
        float aux = Float.parseFloat(Tela.getText());
        Tela.setText(String.valueOf(Math.pow(aux, 2)));
    }//GEN-LAST:event_button_aoQuadradoMouseClicked

    private void button_divPorXMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_divPorXMouseClicked
        float aux = Float.parseFloat(Tela.getText());
        Tela.setText(String.valueOf(1/aux));
    }//GEN-LAST:event_button_divPorXMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tela;
    private javax.swing.JButton button_0;
    private javax.swing.JButton button_1;
    private javax.swing.JButton button_2;
    private javax.swing.JButton button_3;
    private javax.swing.JButton button_4;
    private javax.swing.JButton button_5;
    private javax.swing.JButton button_6;
    private javax.swing.JButton button_7;
    private javax.swing.JButton button_8;
    private javax.swing.JButton button_9;
    private javax.swing.JButton button_C;
    private javax.swing.JButton button_Somar;
    private javax.swing.JButton button_Subtrair;
    private javax.swing.JButton button_aoQuadrado;
    private javax.swing.JButton button_delete;
    private javax.swing.JButton button_divPorX;
    private javax.swing.JButton button_dividir;
    private javax.swing.JButton button_igualdade;
    private javax.swing.JButton button_multiplicar;
    private javax.swing.JButton button_virgula;
    private javax.swing.JButton jButton11;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
